# Copyright 2026 Particular LLC. MOHIO(TM) is a trademark of Particular LLC.
# Licensed under the Mohio Business Source License 1.1 (BSL). See LICENSE.md and LICENSE-SCOPE.md.
"""
mohio_schema.py — Schema manifest generation and validation for Mohio.

Implements Claim 15: Compiler-Native Storage Primitives
- Extracts shape declarations from AST → .mhoschema manifest
- Validates db.* field references against manifest at build time
- Throws SCHEMA_FIELD_UNKNOWN for references to non-existent fields
- No live database connection required at build time

The .mhoschema file is a JSON manifest generated by `mio build` or
`mio schema generate`. It is checked into source control alongside
the .mho source files. The compiler validates field references against
it during `mio check` and before `mio serve`.

Schema manifest format:
{
    "version": "1.0",
    "generated": "ISO timestamp",
    "source": "myapp.mho",
    "tables": {
        "members": {
            "fields": {
                "id":    {"type": "text",   "required": true},
                "email": {"type": "text",   "required": true},
                "name":  {"type": "text",   "required": false},
                "score": {"type": "number", "required": false}
            },
            "shape": "Member"
        }
    }
}
"""

import json
import re
import datetime
from pathlib import Path


# ── Type normalization ─────────────────────────────────────────────────────────

TYPE_MAP = {
    "text":     "text",
    "string":   "text",
    "str":      "text",
    "number":   "number",
    "int":      "number",
    "integer":  "number",
    "float":    "number",
    "decimal":  "number",
    "boolean":  "boolean",
    "bool":     "boolean",
    "datetime": "datetime",
    "date":     "date",
    "time":     "time",
    "uuid":     "text",
    "json":     "json",
    "list":     "json",
}


def normalize_type(t):
    return TYPE_MAP.get((t or "text").lower(), "text")


# ── Schema extraction from AST ─────────────────────────────────────────────────

def extract_schema_from_program(program, source_file=""):
    """
    Walk a transformed Program AST and extract all shape declarations
    into a schema manifest dict.

    Returns: dict matching the .mhoschema format
    """
    from mohio_ast import ShapeDecl, ShapeField, ShapeFieldModifier

    tables = {}

    for stmt in (program.statements or []):
        if not isinstance(stmt, ShapeDecl):
            continue

        shape_name = stmt.name
        # Convention: ShapeName → table name is snake_case plural
        # e.g. Member → members, PaymentData → payment_data
        table_name = _shape_to_table(shape_name)

        fields = {}
        for field in (stmt.fields or []):
            if not isinstance(field, ShapeField):
                continue

            field_type = normalize_type(field.type_name)
            is_required = any(
                str(getattr(m, 'modifier', '') or getattr(m, 'value', '')).lower() == 'required'
                for m in (field.modifiers or [])
            )
            is_never_stored = any(
                'never' in str(getattr(m, 'modifier', '') or getattr(m, 'value', '')).lower()
                for m in (field.modifiers or [])
            )

            fields[field.name] = {
                "type":         field_type,
                "required":     is_required,
                "never_stored": is_never_stored,
            }

        tables[table_name] = {
            "shape":  shape_name,
            "fields": fields,
        }

    return {
        "version":   "1.0",
        "generated": datetime.datetime.utcnow().isoformat() + "Z",
        "source":    str(source_file),
        "tables":    tables,
    }


def _shape_to_table(shape_name):
    """
    Convert PascalCase shape name to snake_case plural table name.
    Member → members
    PaymentData → payment_data
    TransactionRecord → transaction_records
    """
    # Insert underscore before uppercase letters
    s = re.sub(r"(?<!^)(?=[A-Z])", "_", shape_name).lower()
    # Pluralize simply — add s unless ends in s already
    if not s.endswith("s"):
        s += "s"
    return s


# ── Schema manifest I/O ────────────────────────────────────────────────────────

def write_schema(schema, output_path):
    """Write schema manifest to .mhoschema file."""
    path = Path(output_path)
    path.write_text(json.dumps(schema, indent=2))
    return path


def read_schema(schema_path):
    """Read and parse a .mhoschema manifest file."""
    path = Path(schema_path)
    if not path.exists():
        return None
    return json.loads(path.read_text())


def find_schema_file(source_file):
    """
    Find .mhoschema file for a given .mho source file.
    Looks for: same name with .mhoschema extension, then mioschema.json.
    """
    source = Path(source_file)
    candidates = [
        source.with_suffix(".mhoschema"),
        source.parent / "mioschema.json",
        source.parent / ".mhoschema",
    ]
    for c in candidates:
        if c.exists():
            return c
    return None


# ── Field reference validation ─────────────────────────────────────────────────

def validate_field_references(source, schema, filename=""):
    """
    Validate all db.* field references in source against schema manifest.

    Scans source text for patterns like:
        find X in db.TABLE where FIELD is ...
        save to db.TABLE\n    FIELD value

    Returns list of (error_code, message, line_number) tuples.
    Raises nothing — caller decides what to do with errors.
    """
    errors = []
    if not schema:
        return errors

    tables = schema.get("tables", {})
    lines = source.splitlines()

    # Track current db context (which table we're operating on)
    current_table = None
    in_save_block = False
    in_find_block = False

    for lineno, line in enumerate(lines, 1):
        stripped = line.strip()

        # Detect block entry
        find_m = re.match(r"find\s+\w+\s+in\s+db\.(\w+)", stripped)
        if find_m:
            current_table = find_m.group(1)
            in_find_block = True
            in_save_block = False
            if current_table not in tables:
                errors.append(("SCHEMA_TABLE_UNKNOWN",
                    f"db.{current_table} at line {lineno} — "
                    f"table not declared in any shape. "
                    f"Declare: shape {_table_to_shape(current_table)}",
                    lineno))
            continue

        save_m = re.match(r"(?:save|upsert|update)(?:\s+(?:to|in|or update))?\s+db\.(\w+)", stripped)
        if save_m:
            current_table = save_m.group(1)
            in_save_block = True
            in_find_block = False
            if current_table not in tables:
                errors.append(("SCHEMA_TABLE_UNKNOWN",
                    f"db.{current_table} at line {lineno} — "
                    f"table not declared in any shape.",
                    lineno))
            continue

        # Block exit
        if re.match(r"(?:find|save|upsert|update):\s*done", stripped):
            current_table = None
            in_save_block = False
            in_find_block = False
            continue

        # Field reference in where clause
        if in_find_block and current_table and current_table in tables:
            where_m = re.match(r"where\s+(\w+)\s+", stripped)
            if where_m:
                field_name = where_m.group(1)
                table_fields = tables[current_table]["fields"]
                if field_name not in table_fields and field_name not in ("id",):
                    errors.append(("SCHEMA_FIELD_UNKNOWN",
                        f"Field \"{field_name}\" at line {lineno} does not exist "
                        f"in db.{current_table}. "
                        f"Known fields: {', '.join(table_fields.keys())}",
                        lineno))

        # Field assignment in save/update block
        if in_save_block and current_table and current_table in tables:
            # Lines like: "    email   form.email" or "    name value"
            field_m = re.match(r"(\w+)\s+\S", stripped)
            if field_m and not any(kw in stripped for kw in
                ("match", "on.", "save:", "upsert:", "update:", "//", "##")):
                field_name = field_m.group(1)
                table_fields = tables[current_table]["fields"]
                if field_name not in table_fields:
                    errors.append(("SCHEMA_FIELD_UNKNOWN",
                        f"Field \"{field_name}\" at line {lineno} does not exist "
                        f"in db.{current_table}. "
                        f"Known fields: {', '.join(table_fields.keys())}",
                        lineno))

    return errors


def _table_to_shape(table_name):
    """Convert snake_case table name back to PascalCase shape name."""
    return "".join(word.capitalize() for word in table_name.split("_")).rstrip("s")


# ── Public API ─────────────────────────────────────────────────────────────────

def generate_schema(source, source_file=""):
    """
    Parse source and generate schema manifest from shape declarations.
    Returns the schema dict. Does not write to disk.
    """
    from lark import Lark
    from mohio_transformer_ast import transform as ast_transform

    grammar_path = Path(__file__).parent / "mohio.lark"
    grammar = grammar_path.read_text()
    grammar_lines = [l for l in grammar.splitlines() if not l.strip().startswith("//")]
    parser = Lark("\n".join(grammar_lines), parser="earley", ambiguity="resolve")

    try:
        tree = parser.parse(source)
        prog = ast_transform(tree, source)
        return extract_schema_from_program(prog, source_file)
    except Exception as e:
        return {
            "version": "1.0",
            "generated": datetime.datetime.utcnow().isoformat() + "Z",
            "source": str(source_file),
            "tables": {},
            "error": str(e),
        }
